### PR TITLE
Week-3 homework added

### PR DESCRIPTION
**Pull request by hamzakovac995**
CHPT-13

test1.sh
image
test1b.sh
image
badtest1.sh
image
test2.sh
image
badtest2.sh
image
test3.sh
image
test4.sh
image
test5.sh
image
test5b.sh
image
test6.sh
image
test7.sh
image
test8.sh
image
test9.sh
image
test10.sh
image
test11.sh
image
test12.sh
image
test13.sh
image
test14.sh
image
test15.sh
image
test16.sh
image
test16a.sh
image
test17.sh
image
test18.sh
image
test19.sh
image
test20.sh
image
test21.sh
image
badtest3.sh
image
test22.sh
image
test23.sh
image
test24.sh
image
test25.sh
image
test26.sh
image

CHPT-14

test1.sh
image
test2.sh
image
test3.sh
image
test4.sh
image
test5.sh
image
test5b.sh
image
test6.sh
image
test7.sh
image
test8.sh
image
test9.sh
image
badtest1.sh
image
test10.sh
image
test11.sh
image
test12.sh
image
test13.sh
image
test14.sh
image
test15.sh
image
test16.sh
image
test17.sh 
image
test18.sh
image
test19.sh
image
test20.sh
image
test21.sh
image
test22.sh
image
test23.sh
image
test24.sh
image
test25.sh
image
test26.sh
image
test27.sh
image
test28.sh
image

CHPT-15

test
image
test10
image
test11
image
test12
image
test13
image
test14
image
test15
image
test16
image
badtest
image
test17
image
test18
image
test19
image
test20
image
test21
image
test22
image
test23
image

CHPT-16

test1.sh
image
test2.sh
image
test3.sh
image
test3b.sh
image
test4.sh
image
test5.sh
image
test10.sh
image
test13.sh
image
test13b.sh
image

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please check if you miss a Chapter 13 or you just misspell it. 

Remove files from directories which we don't need: " scripts outputs, temp files".

**Comment by hamzakovac995** [comment]
I made a mistake in the description of the pull request. I corrected it. I deleted unnecessary files. Can you check it again?

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please check in directory Chapter-15, file named "test9" is it an output file or a script?

**Comment by hamzakovac995** [comment]
test9 in chpt-15 is output file. I deleted it. Can u check it again please?

**Review by borisbradic — APPROVED** [review]
Approved and merged.

**Pull request merged**
